language: ruby

sudo: false
cache: bundler

before_install:
  - gem update --system
  - gem update bundler

script: 'bundle exec rake test:spec test:remote:spec'

notifications:
  email:
    - kill-bill-commits@googlegroups.com

env:
  global:
    - JRUBY_OPTS='-J-Xmx1024M'

rvm:
  - jruby-1.7.26

gemfile:
  - Gemfile

jdk:
  - openjdk8
