language: ruby

sudo: false
cache: bundler

before_script:
  - bundle exec jbundle install

script: 'bundle exec rake test:spec test:remote:spec'

notifications:
  email:
    - kill-bill-commits@googlegroups.com

env:
  global:
    - JRUBY_OPTS='-J-Xmx1024M'

rvm:
  - jruby-9.0.5.0 

gemfile:
  - Gemfile

jdk:
  - openjdk8
